#!/bin/bash

# Source function library.
. /etc/rc.d/init.d/functions


BIND=127.0.0.1:9000
USER=j
PHP_FCGI_CHILDREN=4
PHP_FCGI_MAX_REQUESTS=500

PHP_CGI=/usr/bin/php-cgi
PHP_CGI_NAME=`basename $PHP_CGI`
PHP_CGI_ARGS="- PATH=/usr/bin PHP_FCGI_CHILDREN=$PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS=$PHP_FCGI_MAX_REQUESTS $PHP_CGI -b $BIND &"
RETVAL=0

start() {
    [ -x $PHP_CGI ] || exit 5
    echo -n $"Starting $PHP_CGI_NAME: "
    daemon --user $USER /bin/env -- $PHP_CGI_ARGS
    retval=$?
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $PHP_CGI_NAME: "
    killproc  $PHP_CGI_NAME
    retval=$?
    echo
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status $PHP_CGI_NAME
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status|status_q)
        rh_$1
        ;;
    condrestart|try-restart)
        rh_status_q || exit 7
        restart
	    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|try-restart}"
        exit 2
esac
